### ISSUE TITLE
LLVM error

### ISSUE THREAD

**Issue by steynh** [riscv-rust/rust#8]
I have now twice gotten the following error when compiling for RISC-V, but I have not yet found out what type of code causes it:

```
rustc: /opt/rust/src/llvm/include/llvm/CodeGen/ValueTypes.h:254: llvm::MVT llvm::EVT::getSimpleVT() const: Assertion `isSimple() && "Expected a SimpleValueType!"' failed.
```

Has anybody got an idea where I should start looking?

EDIT:
I've managed to reproduce the error. When built with the `xargo build --target riscv32i-unknown-none` the following code results in the error:

```rust
#![no_std]
#![crate_type = "staticlib"]

#![cfg_attr(not(test), feature(lang_items))]
#[cfg(not(test))] #[lang = "eh_personality"] #[no_mangle] pub extern fn eh_personality() {}
#[cfg(not(test))] #[lang = "panic_fmt"] #[no_mangle] pub extern fn panic_fmt(args: core::fmt::Arguments) -> ! {
    loop{}
}

extern crate rlibc;

#[no_mangle]
pub extern fn main() {
    let x = return_a_result();
}

fn return_a_result() -> Result<NotSimpleEnum, Error> {
    Ok(NotSimpleEnum::Variant1)
}

enum NotSimpleEnum {
    Variant1,
    Variant2,
    Variant3(u8),
}

enum Error {
    SomeKindOfError,
}
```

The problem seems to be returning a Result with a non-simple enum as ok-type. 

When built with just `xargo build` there are no errors at all.

**Comment by wangrunji0408** [comment]
I got the same error when the code contains `BTreeMap<u8, (u8, u8)>`.
But `BTreeMap<u8, (u16, u16)>` and `(u8, u8)` is OK.

The error occurred again when compiling the [log](https://docs.rs/log/0.4.3/log/) crate. I found it comes from the following function, where `(u8, u8)` appears again.
``` rust
// lib.rs, line 442

// Reimplemented here because std::ascii is not available in libcore
fn eq_ignore_ascii_case(a: &str, b: &str) -> bool {
    fn to_ascii_uppercase(c: u8) -> u8 {
        if c >= b'a' && c <= b'z' {
            c - b'a' + b'A'
        } else {
            c
        }
    }

    if a.len() == b.len() {
        a.bytes()
            .zip(b.bytes())
            // LLVM Error here
            .all(|(a, b)| to_ascii_uppercase(a) == to_ascii_uppercase(b))
    } else {
        false
    }
}
```
If you compile it with `opt-level >= 2`, the error will disappear because `(u8, u8)` is optimized out...

I don't know the exact reason of this problem. But it seems to be containing a non-simple type with a small size (< 4 bytes maybe? ). 

BTW, I'm using the [binary release of riscv-rust toolchain (24 Mar)](https://github.com/riscv-rust/rust/releases/tag/riscv-rust-1.26.0-1-dev). And I didn't reproduce the error with your code.

**Comment by dvc94ch** [comment]
Can this be reproduced with the riscv-rust-pr branch?

**Comment by dvc94ch** [comment]
Please reopen if the issue persists.

RISCV support is now available in the latest nightly. You can compile crates for RISCV using the riscv32imac-unknown-none-elf target and Cargo:
```sh
$ cargo new --lib foo
$ cd foo
$ cat src/lib.rs
```
```rust
#![no_std]

#[no_mangle]
pub fn foo(x: u32, y: u32) -> u32 {
    x + y
}
```
```sh
$ rustup target add riscv32imac-unknown-none-elf
$ cargo build --target riscv32imac-unknown-none-elf --release
$ cargo install cargo-binutils
$ cargo objdump -- -arch-name=riscv32 -d -no-show-raw-insn target/riscv32imac-unknown-none-elf/release/libfoo.rlib
target/riscv32imac-unknown-none-elf/release/libfoo.rlib(foo-5f01dd28752961b9.foo0-d59093d565f158ef2f92ae2d0a10a47.rs.rcgu.o):     file format ELF32-riscv

Disassembly of section .text.foo:
foo:
       0:       add     a0, a1, a0
       4:       ret
```
